/*export const GENDERS = [
  'Masculino',
  'Femenino',
] as const;

export const BLOOD_TYPES = [
  'A+',
  'A-',
  'B+',
  'B-',
  'AB+',
  'AB-',
  'O+',
  'O-',
] as const;*/

export const SPECIALTIES_MOCK = [
        { value: 'Cardiologia', id: 1 },
        { value: 'Pediatría', id: 2 },
        { value: 'Dermatología', id: 3 },
        { value: 'Neurología', id: 4 },
        { value: 'Traumatología', id: 5 },
        { value: 'Medicina Interna', id: 6 },
        { value: 'Cirugía General', id: 7 },
        { value: 'Ginecología', id: 8 },
        { value: 'Oncología', id: 9 },
        { value: 'Oftalmología', id: 10 },
        { value: 'Otorrinolaringología', id: 11 },
        { value: 'Psiquiatría', id: 12 },
        { value: 'Radiología', id: 13 },
        { value: 'Urología', id: 14 },
        { value: 'Anestesiología', id: 15 },
        { value: 'Cirugía Plástica', id: 16 },
        { value: 'Dental', id: 17 },
        { value: 'Nutrición', id: 18 },
        { value: 'Fisioterapia', id: 19 },
        { value: 'Terapia Ocupacional', id: 20 },
        { value: 'Psicología', id: 21 },
        { value: 'Podología', id: 22 },
        { value: 'Farmacia', id: 23 },
        { value: 'Laboratorio', id: 24 },
        { value: 'Imagenología', id: 25 },
        { value: 'Servicio Social', id: 26 },
        { value: 'Otro', id: 27 },
      ]