export const GENERIC_ERROR_CODES = {

  DATA_INTEGRITY_ERROR: 'DATA_INTEGRITY_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

} as const;

export const PROBLEM_CODES = {

  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_DOCUMENT_ALREADY_EXISTS: 'PATIENT_DOCUMENT_ALREADY_EXISTS',
  PATIENT_EMAIL_ALREADY_EXISTS: 'PATIENT_EMAIL_ALREADY_EXISTS',

} as const;